name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto green
        env:
          USER_EMAIL: ${{ secrets.EMAIL }}
        run: |
          messages=("Update documentation :art:" "a commit a day keeps your girlfriend away:checked_flag:" "Fix typo in README :zap:“:racehorse:" "Add unit tests for module X :fire:" "Refactor function Y for better performance :bug:" "Implement feature Z" "Update dependencies :ambulance:" "Improve error handling :sparkles:" "Optimize database queries :memo:" "Add missing comments :rocket:" "Adjust layout for mobile devices :tada:" "Resolve merge conflict :white_check_mark:" "Bump version number :lock:")
          idx=$((RANDOM % ${#messages[@]}))
          COMMIT_MESSAGE="${messages[$idx]}"
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "$COMMIT_MESSAGE"
          git push
